# Generated by Django 3.0.7 on 2020-06-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_attendance_image_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_image',
            name='nb_p',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
