# Generated by Django 3.0.7 on 2020-07-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_attendance_image_nb_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_detail',
            old_name='date',
            new_name='date_p',
        ),
    ]
