# Generated by Django 3.0.7 on 2020-07-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200703_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_detail',
            name='date_p',
            field=models.DateField(blank=True),
        ),
    ]
