# Generated by Django 3.0.7 on 2020-07-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200703_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_detail',
            old_name='date_p',
            new_name='date',
        ),
    ]
