# Generated by Django 3.0.7 on 2020-07-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200703_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_image',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
