# Generated by Django 3.0.7 on 2020-06-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(default='teacher', max_length=255),
        ),
    ]
